version: '3'

services:
  db:
    image: mysql
    container_name: mysql_database
    ports:
      - '3306:3306'
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE : bookchat
      MYSQL_ROOT_PASSWORD : ${DB_PASSWORD}
    networks:
      - bookchat_network
  spring:
    depends_on:
      - db
    restart: always
    container_name: bookchat-application
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      AWS_S3_ACCESSKEY: ${AWS_S3_ACCESSKEY}
      AWS_S3_SECRETKEY: ${AWS_S3_SECRETKEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      KAKAO_SECRET: ${KAKAO_SECRET}
      KAKAO_BASE_URL: ${KAKAO_BASE_URL}

    networks:
      - bookchat_network
networks:
  bookchat_network:


