spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/bookchat
    username: bookchat
    password: pw
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true