spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

jwt:
  secret: ${JWT_SECRET}

kakao:
  secret: ${KAKAO_SECRET}
  baseurl: ${KAKAO_BASE_URL}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_S3_ACCESSKEY}
      secretKey: ${AWS_S3_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
